### ISSUE TITLE
Required courses show up in the 'remaining' courses section

### ISSUE THREAD

**Issue by CryptidGrrrl** [anderm18/HASSPathways#142]
For certain pathways, you have to take one or more required courses and take the rest of your credits from a list of 'remaining' courses. In certain pathways, the required courses also show up as an option under 'remaining'. This doesn't make sense, because if the course is required it cannot be used as a 'remaining' option.

This can be seen in the "studio arts" pathway, "art history ARTS-1050" shows up under required and also remaining. Is this an issue from the course catalog, or is something weird going on with the remaining course display?

**Comment by ACE3R2** [comment]
This seems to be an issue with how we parse the catalog. For this example, it's because the catalog specifies "any 1000-level arts elective" as an option for the remaining courses, and we don't specifically check whether it is already in the required section, so that should be a relatively easy fix.
