### ISSUE TITLE
Selecting some courses adds multiple courses in the pathway

### ISSUE THREAD

**Issue by liuj-42** [anderm18/HASSPathways#34]
2 examples:
Under the Arts History pathway, under the 1st course selecting the "Art History" course will show "Art History" and "Art Histories" classes on the "My Pathways" page

Under the Arts History pathway, under the 2nd course selecting the "History of Western Music" course will show "History of Western Music" and "Histories of Western Music" courses on the "My Pathways" page

Deselecting either course will remove both of the courses shown in the "My Pathways" page too.

Here is a link to a video of me demonstrating it: https://streamable.com/xiumc9

**Comment by CryptidGrrrl** [comment]
This is likely an issue with the info in the JSON file since those classes are under the same course code (both of the art history classes are ARTS-2500). We may have to remove classes with duplicate course codes after scraping the data into the JSON, but I'm not sure how this would affect things with the admin portal and an admin adding a course in that might be a duplicate

**Comment by liuj-42** [comment]
this was fixed a while ago
